# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-22 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20181022_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='message',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
