# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-22 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_remove_chores_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chores',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
