# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-22 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_chores_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chores',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='login.Users'),
            preserve_default=False,
        ),
    ]
